### PR TITLE
Constrict job scheduler configuration options

### LINKED ISSUE #223: [BUG] Infinite loop when using a negative value for `job.schedule`
**Describe the bug**
The CM enters an infinite loop when a negative value is set for the `job.schedule` setting.

**To Reproduce**
- See https://github.com/wazuh/wazuh-indexer-plugins/pull/213#issuecomment-2596068762

**Expected behavior**
- No negative values are allowed for this setting.
- No infinite loop when using a custom value for this setting.
- The CM validates that this setting is under the expected working window.

**Plugins**
Command Manager.

**Additional context**
https://github.com/wazuh/wazuh-indexer-plugins/pull/213#issuecomment-2596068762

### LINKED ISSUE #224: [BUG] Search job is not executed when using a negative value for `job.pit_keep_alive`
**Describe the bug**
The CM enters an infinite loop when a negative value is set for the `job.schedule` setting.

**To Reproduce**
- See https://github.com/wazuh/wazuh-indexer-plugins/pull/213#issuecomment-2595711671

**Expected behavior**
- No negative values are allowed for this setting.
- The CM works regularly when using a custom value for this setting.
- The CM validates that this setting is under the expected working window.

**Plugins**
Command Manager.

**Additional context**
https://github.com/wazuh/wazuh-indexer-plugins/pull/213#issuecomment-2595711671

### PR DESCRIPTION
**Pull request by f-galland**
### Description
This PR fixes bugs triggered by certain combinations of values in the command manager settings.

### Issues Resolved
Closes #223
Closes #224

### CODE REVIEW

File: plugins/command-manager/src/main/java/com/wazuh/commandmanager/settings/PluginSettings.java [hunk 1]
```diff
@@ -81,10 +85,21 @@ private PluginSettings(@NonNull final Settings settings) {
...
-        this.jobKeepAlive = JOB_KEEP_ALIVE.get(settings);
+        this.pitKeepAlive = this.jobSchedule * 60;
+        this.validateSettings();
         log.debug("Settings loaded: {}", this.toString());
     }
 
+    /** Fits setting values to the internal logic */
+    private void validateSettings() {
+        // If timeout is not less than job period in seconds
+        if (!(this.timeout < this.jobSchedule * 60)) {
```
Comment (AlexRuiz7) [inline plugins/command-manager/src/main/java/com/wazuh/commandmanager/settings/PluginSettings.java:96]: Could use `this.pitKeepAlive` to save this multiply operation.

File: plugins/command-manager/src/main/java/com/wazuh/commandmanager/settings/PluginSettings.java [hunk 2]
```diff
@@ -81,10 +85,21 @@ private PluginSettings(@NonNull final Settings settings) {
...
+            // Set timeout to half job period (in seconds)
+            this.timeout = this.jobSchedule * 30;
+            log.info("Setting command_manager.client.timeout to half command_manager.job.schedule (in seconds): {}", this.timeout);
```
Comment (AlexRuiz7) [inline plugins/command-manager/src/main/java/com/wazuh/commandmanager/settings/PluginSettings.java:99]: I'd be confused seeing this log, as no reason is given. We could maybe add 2 logs

- warn: notifies about invalid/unrecommended settings
- info: notifies about the action taken to fix that

**Review by AlexRuiz7 — APPROVED** [review]
- Code review: ✔️ 
- Tests: ✔️
