### PR TITLE
Fix overwrite of content offset on each start

### LINKED ISSUE #400: [BUG] Content initialized from a snapshot on every start
**Describe the bug**
The Content Manager is downloading and indexing the CTI snapshot on every start of the node.

**To Reproduce**
1. Install the latest package.
2. Start the wazuh-indexer process.
3. Wait for the content to be initialized.
4. Restart the service.
5. The snapshot is downloaded and indexed again. 🔴 

**Expected behavior**
As the flow described in https://github.com/wazuh/wazuh-indexer-plugins/issues/358, the content should only be initialized from snapshot, if and only if, its offset is equal to 0.

**Plugins**
Content Manager.

**Additional context**
The Content Manager fetches the latest information for the configured consumer on start. This is expected and correct, however, during the process to set the `latest_offset` value, it overwrites the `offset`, setting it 0 (the default value).

https://github.com/wazuh/wazuh-indexer-plugins/blob/3b429644a1973155b98848ed1ca683199eb7bc74/plugins/content-manager/src/main/java/com/wazuh/contentmanager/client/CTIClient.java#L170

### PR DESCRIPTION
**Pull request by AlexRuiz7**
### Description
This PR fixes the overwrite of the offset on each start of the wazuh-indexer service.

#### Useful commands for testing

```
# Change log level
curl -k -u admin:admin -XPUT "https://192.168.56.11:9200/_cluster/settings" -H 'Content-Type: application/json' -d'
{
  "persistent" : {
    "logger.org.opensearch" : "ERROR",
    "logger.com.wazuh.contentmanager" : "INFO"
  }
}
'

# Set consumer's offset to 0 to force a reinitialization.
curl -XPOST -k -u admin:admin "https://192.168.56.11:9200/wazuh-context/_update/vd_1.0.0" -H 'Content-Type: application/json' -d'
{
  "doc": {
    "vd_4.8.0": {
      "last_offset": 1901695,
      "last_snapshot_link": "https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1901695_1746459961.zip",
      "offset": 0
    }
  }
}
'

# Delete indices to force a reinitialization
curl -XDELETE -k -u admin:admin "https://192.168.56.11:9200/wazuh-context"
curl -XDELETE -k -u admin:admin "https://192.168.56.11:9200/wazuh-cve"
```

#### Evidence

1. Initialization from snapshot at cluster's start.
```log
[2025-05-07T16:00:34,334][INFO ][c.w.c.i.ContextIndex     ] [node-2] Fetched consumer from the [wazuh-context] index: ConsumerInfo{context='vd_1.0.0', name='vd_4.8.0', offset=0, lastOffset=1913009, lastSnapshotLink='https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1901695_1746459961.zip'}
[2025-05-07T16:00:34,439][INFO ][o.o.i.r.RecoverySourceHandler] [node-2] [wazuh-context][0][recover to node-1] finalizing recovery took [78.9ms]
[2025-05-07T16:00:34,522][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [node-2] Cancelling the migration process.
[2025-05-07T16:00:34,613][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [node-2] Cancelling the migration process.
[2025-05-07T16:00:34,664][INFO ][c.w.c.c.CTIClient        ] [node-2] Operation succeeded: status code 200 - {"data":{"id":4,"name":"vd_4.8.0","context":"vd_1.0.0","operations":null,"inserted_at":"2023-11-23T19:34:18.698495Z","updated_at":"2025-05-07T14:15:17.291331Z","paths_filter":null,"changes_url":"cti.wazuh.com/api/v1/catalog/contexts/vd_1.0.0/consumers/vd_4.8.0/changes","last_offset":1913009,"last_snapshot_at":"2025-05-05T15:46:01.391685Z","last_snapshot_link":"https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1901695_1746459961.zip","last_snapshot_offset":1901695}}
[2025-05-07T16:00:34,665][INFO ][c.w.c.u.SnapshotManager  ] [node-2] Current consumer info: ConsumerInfo{context='vd_1.0.0', name='vd_4.8.0', offset=0, lastOffset=1913009, lastSnapshotLink='https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1901695_1746459961.zip'}
[2025-05-07T16:00:34,665][INFO ][c.w.c.u.SnapshotManager  ] [node-2] Latest consumer info: ConsumerInfo{context='vd_1.0.0', name='vd_4.8.0', offset=0, lastOffset=1913009, lastSnapshotLink='https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1901695_1746459961.zip'}
[2025-05-07T16:00:34,665][INFO ][c.w.c.u.SnapshotManager  ] [node-2] Initializing consumer: ConsumerInfo{context='vd_1.0.0', name='vd_4.8.0', offset=0, lastOffset=1913009, lastSnapshotLink='https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1901695_1746459961.zip'}
[2025-05-07T16:00:34,682][INFO ][c.w.c.u.SnapshotManager  ] [node-2] Successfully initialized consumer [vd_1.0.0][vd_4.8.0]
[2025-05-07T16:00:34,682][INFO ][c.w.c.u.SnapshotManager  ] [node-2] Initializing [wazuh-cve] index from a snapshot
[2025-05-07T16:00:34,682][INFO ][c.w.c.c.CTIClient        ] [node-2] Starting snapshot download from [https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1901695_1746459961.zip]
[2025-05-07T16:00:35,471][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [node-2] Cancelling the migration process.
[2025-05-07T16:00:41,893][INFO ][c.w.c.c.CTIClient        ] [node-2] Snapshot downloaded to /tmp/opensearch-7816041565507332050/1901695_1746459961.zip
[2025-05-07T16:00:46,191][INFO ][c.w.c.u.Unzip            ] [node-2] [/tmp/opensearch-7816041565507332050/1901695_1746459961.zip] filePath unzipped to [/tmp/opensearch-7816041565507332050]
[2025-05-07T16:02:08,633][INFO ][c.w.c.i.ContentIndex     ] [node-2] Snapshot indexing finished successfully in 82441 ms
[2025-05-07T16:02:08,742][WARN ][c.w.c.c.CommandManagerClient] [node-2] Unexpected response code: 401
[2025-05-07T16:05:32,010][INFO ][o.o.j.s.JobSweeper       ] [node-2] Running full sweep
[2025-05-07T16:05:32,411][INFO ][o.o.i.i.PluginVersionSweepCoordinator] [node-2] Canceling sweep ism plugin version job
^N[2025-05-07T16:10:32,012][INFO ][o.o.j.s.JobSweeper       ] [node-2] Running full sweep
```

2. Initialization from snapshot when offset is set to 0.
```log
[2025-05-07T16:16:37,672][INFO ][c.w.c.c.CTIClient        ] [node-2] Operation succeeded: status code 200 - {"data":{"id":4,"name":"vd_4.8.0","context":"vd_1.0.0","operations":null,"inserted_at":"2023-11-23T19:34:18.698495Z","updated_at":"2025-05-07T14:15:17.291331Z","last_offset":1913009,"paths_filter":null,"changes_url":"cti.wazuh.com/api/v1/catalog/contexts/vd_1.0.0/consumers/vd_4.8.0/changes","last_snapshot_at":"2025-05-05T15:46:01.391685Z","last_snapshot_link":"https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1901695_1746459961.zip","last_snapshot_offset":1901695}}
[2025-05-07T16:16:37,673][INFO ][c.w.c.u.SnapshotManager  ] [node-2] Current consumer info: ConsumerInfo{context='vd_1.0.0', name='vd_4.8.0', offset=0, lastOffset=1901695, lastSnapshotLink='https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1901695_1746459961.zip'}
[2025-05-07T16:16:37,673][INFO ][c.w.c.u.SnapshotManager  ] [node-2] Latest consumer info: ConsumerInfo{context='vd_1.0.0', name='vd_4.8.0', offset=0, lastOffset=1913009, lastSnapshotLink='https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1901695_1746459961.zip'}
[2025-05-07T16:16:37,673][INFO ][c.w.c.u.SnapshotManager  ] [node-2] Initializing consumer: ConsumerInfo{context='vd_1.0.0', name='vd_4.8.0', offset=0, lastOffset=1913009, lastSnapshotLink='https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1901695_1746459961.zip'}
[2025-05-07T16:16:37,684][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [node-2] Cancelling the migration process.
[2025-05-07T16:16:37,688][INFO ][c.w.s.i.WazuhIndices     ] [node-2] Index template created successfully: index-template-hotfixes true
[2025-05-07T16:16:37,742][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [node-2] Cancelling the migration process.
[2025-05-07T16:16:37,748][INFO ][c.w.s.i.WazuhIndices     ] [node-2] Index template created successfully: index-template-cve true
[2025-05-07T16:16:37,910][INFO ][o.o.p.PluginsService     ] [node-2] PluginService:onIndexModule index:[wazuh-states-inventory-processes/XUkgJFFCRN-avNY2LGYryQ]
[2025-05-07T16:16:37,922][INFO ][o.o.p.PluginsService     ] [node-2] PluginService:onIndexModule index:[wazuh-states-sca/mAPtvJTRRfq6eVNbrJqnhQ]
[2025-05-07T16:16:37,927][INFO ][o.o.p.PluginsService     ] [node-2] PluginService:onIndexModule index:[wazuh-states-inventory-hotfixes/OHS6eYIsTReveJ9Ju5OHHg]
[2025-05-07T16:16:37,930][INFO ][o.o.p.PluginsService     ] [node-2] PluginService:onIndexModule index:[wazuh-states-inventory-ports/-NsMe4ePQIe4ID4mogU1Ng]
[2025-05-07T16:16:38,061][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [node-2] Cancelling the migration process.
[2025-05-07T16:16:38,066][INFO ][c.w.s.i.WazuhIndices     ] [node-2] Index template created successfully: index-template-ports true
[2025-05-07T16:16:38,066][INFO ][c.w.c.u.SnapshotManager  ] [node-2] Successfully initialized consumer [vd_1.0.0][vd_4.8.0]
[2025-05-07T16:16:38,066][INFO ][c.w.c.u.SnapshotManager  ] [node-2] Initializing [wazuh-cve] index from a snapshot
[2025-05-07T16:16:38,067][INFO ][c.w.c.c.CTIClient        ] [node-2] Starting snapshot download from [https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1901695_1746459961.zip]
[2025-05-07T16:16:38,068][INFO ][o.o.s.l.LogTypeService   ] [node-2] Loaded [432] field mapping docs successfully!
[2025-05-07T16:16:38,074][INFO ][o.o.s.l.LogTypeService   ] [node-2] Indexing [23] customLogTypes
[2025-05-07T16:16:38,093][INFO ][o.o.s.l.LogTypeService   ] [node-2] Loaded [23] customLogType docs successfully!
[2025-05-07T16:16:38,093][INFO ][o.o.s.SecurityAnalyticsPlugin] [node-2] LogType config index successfully created and builtin log types loaded
[2025-05-07T16:16:38,151][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [node-2] Cancelling the migration process.
[2025-05-07T16:16:38,155][INFO ][c.w.s.i.WazuhIndices     ] [node-2] Index template created successfully: index-template-sca true
[2025-05-07T16:16:38,221][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [node-2] Cancelling the migration process.
[2025-05-07T16:16:38,227][INFO ][c.w.s.i.WazuhIndices     ] [node-2] Index template created successfully: index-template-agent true
[2025-05-07T16:16:38,307][INFO ][o.o.p.PluginsService     ] [node-2] PluginService:onIndexModule index:[wazuh-states-vulnerabilities/ewa3FxVGSQ-4FpaCJ75NUQ]
[2025-05-07T16:16:38,334][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [node-2] Cancelling the migration process.
[2025-05-07T16:16:38,339][INFO ][c.w.s.i.WazuhIndices     ] [node-2] Index template created successfully: index-template-fim true
[2025-05-07T16:16:38,343][INFO ][c.w.s.i.WazuhIndices     ] [node-2] Index template created successfully: index-template-scheduled-commands true
[2025-05-07T16:16:38,346][INFO ][c.w.s.i.WazuhIndices     ] [node-2] Index template created successfully: index-template-processes true
[2025-05-07T16:16:38,360][INFO ][c.w.s.i.WazuhIndices     ] [node-2] Index template created successfully: index-template-alerts true
[2025-05-07T16:16:38,364][INFO ][c.w.s.i.WazuhIndices     ] [node-2] Index template created successfully: index-template-commands true
[2025-05-07T16:16:38,414][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [node-2] Cancelling the migration process.
[2025-05-07T16:16:38,419][INFO ][c.w.s.i.WazuhIndices     ] [node-2] Index template created successfully: index-template-hardware true
[2025-05-07T16:16:38,423][INFO ][c.w.s.i.WazuhIndices     ] [node-2] Index template created successfully: index-template-system true
[2025-05-07T16:16:38,426][INFO ][c.w.s.i.WazuhIndices     ] [node-2] Index template created successfully: index-template-users true
[2025-05-07T16:16:38,429][INFO ][c.w.s.i.WazuhIndices     ] [node-2] Index template created successfully: index-template-packages true
[2025-05-07T16:16:38,432][INFO ][c.w.s.i.WazuhIndices     ] [node-2] Index template created successfully: index-template-networks true
[2025-05-07T16:16:38,440][INFO ][o.o.o.i.ObservabilityIndex] [node-2] observability:Index .opensearch-observability update mapping Acknowledged
[2025-05-07T16:16:38,899][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [node-2] Cancelling the migration process.
[2025-05-07T16:16:38,948][INFO ][o.o.p.PluginsService     ] [node-2] PluginService:onIndexModule index:[.opensearch-observability/jcNP-zSySMmNN7uOARUrwg]
[2025-05-07T16:16:38,953][INFO ][o.o.p.PluginsService     ] [node-2] PluginService:onIndexModule index:[wazuh-context/sATLO43pQ8STnmuc7X4U6A]
[2025-05-07T16:16:39,010][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [node-2] Cancelling the migration process.
[2025-05-07T16:16:40,202][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [node-2] Cancelling the migration process.
[2025-05-07T16:16:40,255][INFO ][o.o.p.PluginsService     ] [node-2] PluginService:onIndexModule index:[.opensearch-sap-log-types-config/7Jqf0IpRTYqaQHTWpsxDOw]
[2025-05-07T16:16:40,318][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [node-2] Cancelling the migration process.
[2025-05-07T16:16:40,409][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [node-2] Cancelling the migration process.
[2025-05-07T16:16:40,662][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [node-2] Cancelling the migration process.
[2025-05-07T16:16:43,762][INFO ][c.w.c.c.CTIClient        ] [node-2] Snapshot downloaded to /tmp/opensearch-18067938492832330497/1901695_1746459961.zip
[2025-05-07T16:16:47,947][INFO ][c.w.c.u.Unzip            ] [node-2] [/tmp/opensearch-18067938492832330497/1901695_1746459961.zip] filePath unzipped to [/tmp/opensearch-18067938492832330497]
[2025-05-07T16:17:44,273][INFO ][c.w.c.i.ContentIndex     ] [node-2] Snapshot indexing finished successfully in 56324 ms
[2025-05-07T16:17:44,370][WARN ][c.w.c.c.CommandManagerClient] [node-2] Unexpected response code: 401

```

3. No initialization when offset != 0
```log
[2025-05-07T16:15:20,726][INFO ][c.w.s.i.WazuhIndices     ] [node-2] Index template created successfully: index-template-vulnerabilities true
[2025-05-07T16:15:20,769][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [node-2] Cancelling the migration process.
[2025-05-07T16:15:20,774][INFO ][c.w.s.i.WazuhIndices     ] [node-2] Index template created successfully: index-template-hotfixes true
[2025-05-07T16:15:20,782][INFO ][c.w.c.c.CTIClient        ] [node-2] Operation succeeded: status code 200 - {"data":{"id":4,"name":"vd_4.8.0","context":"vd_1.0.0","operations":null,"inserted_at":"2023-11-23T19:34:18.698495Z","updated_at":"2025-05-07T14:15:17.291331Z","paths_filter":null,"last_offset":1913009,"changes_url":"cti.wazuh.com/api/v1/catalog/contexts/vd_1.0.0/consumers/vd_4.8.0/changes","last_snapshot_at":"2025-05-05T15:46:01.391685Z","last_snapshot_link":"https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1901695_1746459961.zip","last_snapshot_offset":1901695}}
[2025-05-07T16:15:20,783][INFO ][c.w.c.u.SnapshotManager  ] [node-2] Current consumer info: ConsumerInfo{context='vd_1.0.0', name='vd_4.8.0', offset=1901647, lastOffset=1913009, lastSnapshotLink='https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1901695_1746459961.zip'}
[2025-05-07T16:15:20,783][INFO ][c.w.c.u.SnapshotManager  ] [node-2] Latest consumer info: ConsumerInfo{context='vd_1.0.0', name='vd_4.8.0', offset=0, lastOffset=1913009, lastSnapshotLink='https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1901695_1746459961.zip'}
[2025-05-07T16:15:20,783][INFO ][c.w.c.u.SnapshotManager  ] [node-2] Consumer already initialized (offset 1901647 != 0). Skipping...
[2025-05-07T16:15:20,933][INFO ][o.o.p.PluginsService     ] [node-2] PluginService:onIndexModule index:[wazuh-states-inventory-processes/XUkgJFFCRN-avNY2LGYryQ]
[2025-05-07T16:15:20,946][INFO ][o.o.p.PluginsService     ] [node-2] PluginService:onIndexModule index:[wazuh-states-sca/mAPtvJTRRfq6eVNbrJqnhQ]
[2025-05-07T16:15:20,952][INFO ][o.o.p.PluginsService     ] [node-2] PluginService:onIndexModule index:[wazuh-states-inventory-hotfixes/OHS6eYIsTReveJ9Ju5OHHg]
[2025-05-07T16:15:20,956][INFO ][o.o.p.PluginsService     ] [node-2] PluginService:onIndexModule index:[wazuh-states-inventory-ports/-NsMe4ePQIe4ID4mogU1Ng]
[2025-05-07T16:15:21,062][INFO ][o.o.a.u.d.DestinationMigrationCoordinator] [node-2] Cancelling the migration process.
[2025-05-07T16:15:21,081][INFO ][o.o.s.l.LogTypeService   ] [node-2] Loaded [432] field mapping docs successfully!
[2025-05-07T16:15:21,095][INFO ][c.w.s.i.WazuhIndices     ] [node-2] Index template created successfully: index-template-cve true
```

### Issues Resolved
Closes #400

### CODE REVIEW

File: plugins/content-manager/src/main/java/com/wazuh/contentmanager/utils/SnapshotManager.java [hunk 1]
```diff
@@ -138,47 +148,68 @@ protected DirectoryStream<Path> getStream(Path outputDir) throws IOException {
...
 
-        if (consumerInfo == null) {
-            throw new IOException("Consumer Information is null. Skipping indexing");
-        }
-        IndexResponse response = this.contextIndex.index(consumerInfo);
+        // testy test test
+        //        current = new ConsumerInfo(latest);
+        //        current.setOffset(1899747);
+        //        this.contextIndex.index(current);
+        // testy test test
```
Comment (Jorgesnchz) [inline plugins/content-manager/src/main/java/com/wazuh/contentmanager/utils/SnapshotManager.java:167]: This lines can be deleted

File: plugins/content-manager/src/test/java/com/wazuh/contentmanager/client/CTIClientTests.java [hunk 2]
```diff
@@ -63,17 +64,20 @@ public void tearDown() throws Exception {
         super.tearDown();
     }
 
+    /** */
```
Comment (Jorgesnchz) [inline plugins/content-manager/src/test/java/com/wazuh/contentmanager/client/CTIClientTests.java:67]: Missing JavaDoc

File: plugins/content-manager/src/test/java/com/wazuh/contentmanager/client/CTIClientTests.java [hunk 3]
```diff
@@ -100,18 +104,21 @@ public void testSendRequest_SuccessfulRequest() {
                         eq(3));
     }
 
+    /** */
```
Comment (Jorgesnchz) [inline plugins/content-manager/src/test/java/com/wazuh/contentmanager/client/CTIClientTests.java:107]: Missing JavaDoc

File: plugins/content-manager/src/test/java/com/wazuh/contentmanager/client/CTIClientTests.java [hunk 4]
```diff
@@ -128,20 +135,23 @@ public void testSendRequest_BadRequest() {
         assertEquals(HttpStatus.SC_BAD_REQUEST, response.getCode());
     }
 
+    /** */
```
Comment (Jorgesnchz) [inline plugins/content-manager/src/test/java/com/wazuh/contentmanager/client/CTIClientTests.java:138]: Missing JavaDoc

File: plugins/content-manager/src/test/java/com/wazuh/contentmanager/client/CTIClientTests.java [hunk 5]
```diff
@@ -167,46 +177,72 @@ public void testSendRequest_TooManyRequests_RetriesThreeTimes() {
                         isNull());
     }
 
-    public void testGetCatalog_SuccessfulRequest() {
+    /**
+     * @throws IOException
+     */
+    public void testGetConsumerInfo_SuccessfulRequest() throws IOException {
```
Comment (Jorgesnchz) [inline plugins/content-manager/src/test/java/com/wazuh/contentmanager/client/CTIClientTests.java:183]: Missing JavaDoc

File: plugins/content-manager/src/test/java/com/wazuh/contentmanager/client/CTIClientTests.java [hunk 6]
```diff
@@ -167,46 +177,72 @@ public void testSendRequest_TooManyRequests_RetriesThreeTimes() {
...
+            anyMap(),
+            any(Header.class)))
+        .thenReturn(null);
+        // spotless:on
+
+        // Act & Assert
+        assertThrows(HttpHostConnectException.class, () -> this.spyCtiClient.getConsumerInfo());
     }
 
+    /** */
```
Comment (Jorgesnchz) [inline plugins/content-manager/src/test/java/com/wazuh/contentmanager/client/CTIClientTests.java:229]: Missing JavaDoc

File: plugins/content-manager/src/test/java/com/wazuh/contentmanager/client/CTIClientTests.java [hunk 7]
```diff
@@ -216,15 +252,23 @@ public void testGetChanges_SuccessfulRequest() {
                 .sendRequest(any(Method.class), anyString(), isNull(), anyMap(), isNull(), anyInt());
     }
 
+    /** */
```
Comment (Jorgesnchz) [inline plugins/content-manager/src/test/java/com/wazuh/contentmanager/client/CTIClientTests.java:255]: Missing JavaDoc

**Review by Jorgesnchz — CHANGES_REQUESTED** [review]
LGTM, just minor changes needed

File: plugins/content-manager/src/main/java/com/wazuh/contentmanager/index/ContextIndex.java [hunk 8]
```diff
@@ -77,10 +78,14 @@ public IndexResponse index(ConsumerInfo consumerInfo) {
...
                             .id(consumerInfo.getContext());
 
-            // Set this to null so that future get() operation needs to read from the index
-            this.consumerInfo = null;
-
-            return this.client.index(indexRequest).get(TIMEOUT, TimeUnit.SECONDS);
+            IndexResponse indexResponse =
+                    this.client.index(indexRequest).get(PluginSettings.TIMEOUT, TimeUnit.SECONDS);
+            if (indexResponse.getResult() == DocWriteResponse.Result.CREATED
+                    || indexResponse.getResult() == DocWriteResponse.Result.UPDATED) {
```
[the remark this answers is not in the document]
Comment (AlexRuiz7) [reply plugins/content-manager/src/main/java/com/wazuh/contentmanager/index/ContextIndex.java:84]: Maybe. @QU3B1M what do you think?

File: plugins/content-manager/src/main/java/com/wazuh/contentmanager/utils/SnapshotManager.java [hunk 9]
```diff
@@ -51,45 +52,53 @@ public class SnapshotHelper {
...
-     * Alternate constructor that allows injecting CTIClient for test purposes.
+     * Alternate constructor that allows injecting CTIClient for test purposes. Dependency injection.
      *
      * @param ctiClient Instance of CTIClient.
      * @param environment Needed for snapshot file handling.
      * @param contextIndex Handles context and consumer related metadata.
      * @param contentIndex Handles indexed content.
      */
-    protected SnapshotHelper(
+    protected SnapshotManager(
```
[the remark this answers is not in the document]
Comment (AlexRuiz7) [reply plugins/content-manager/src/main/java/com/wazuh/contentmanager/utils/SnapshotManager.java:75]: Not really needed I think.

File: plugins/content-manager/src/main/java/com/wazuh/contentmanager/index/ContextIndex.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (QU3B1M) [reply plugins/content-manager/src/main/java/com/wazuh/contentmanager/index/ContextIndex.java:84]: In this case we are using the `Client#index()` method that will only create or update a document, so we dont need to validate the `DELETED` type, anyway if we could add this validation in the `delete()` methods (I think it is only the case of the `ContentIndex` class )

File: plugins/content-manager/src/main/java/com/wazuh/contentmanager/utils/SnapshotManager.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (QU3B1M) [reply plugins/content-manager/src/main/java/com/wazuh/contentmanager/utils/SnapshotManager.java:75]: In fact the `@VisibleForTesting` is not required, it is an optional "flag" typically used in methods without access modifiers (`protected`/`public`/`private) which are by default `package-private`, having it we know that the method is configured this way to be able to test it.

**Comment by Jorgesnchz** [comment]
Tested performed: 

## Initialization from snapshot at cluster's start. :green_circle: 
```
[2025-05-09T11:19:32,522][INFO ][c.w.c.u.SnapshotManager  ] [node-1] Successfully initialized consumer [vd_1.0.0][vd_4.8.0]
[2025-05-09T11:19:32,523][INFO ][c.w.c.u.SnapshotManager  ] [node-1] Initializing [wazuh-cve] index from a snapshot
[2025-05-09T11:19:32,523][INFO ][c.w.c.c.CTIClient        ] [node-1] Starting snapshot download from [https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1901695_1746459961.zip]
[2025-05-09T11:19:35,413][INFO ][c.w.c.c.CTIClient        ] [node-1] Snapshot downloaded to /tmp/opensearch-16114092523728566914/1901695_1746459961.zip
[2025-05-09T11:19:50,702][INFO ][o.o.m.c.MLSyncUpCron     ] [node-1] ML configuration initialized successfully
[2025-05-09T11:19:52,434][INFO ][c.w.c.u.Unzip            ] [node-1] [/tmp/opensearch-16114092523728566914/1901695_1746459961.zip] filePath unzipped to [/tmp/opensearch-16114092523728566914]
[2025-05-09T11:21:33,366][INFO ][c.w.c.i.ContentIndex     ] [node-1] Snapshot indexing finished successfully in 100931 ms
[2025-05-09T11:21:33,407][WARN ][c.w.c.c.CommandManagerClient] [node-1] Unexpected response code: 401
[2025-05-09T11:24:26,928][INFO ][o.o.j.s.JobSweeper       ] [node-1] Running full sweep
```

## Initialization from snapshot when offset is set to 0. :green_circle: 
```
[2025-05-09T11:40:35,716][INFO ][c.w.c.u.SnapshotManager  ] [node-1] Successfully initialized consumer [vd_1.0.0][vd_4.8.0]
[2025-05-09T11:40:35,716][INFO ][c.w.c.u.SnapshotManager  ] [node-1] Initializing [wazuh-cve] index from a snapshot
[2025-05-09T11:40:35,717][INFO ][c.w.c.c.CTIClient        ] [node-1] Starting snapshot download from [https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1901695_1746459961.zip]
[2025-05-09T11:40:39,685][INFO ][c.w.c.c.CTIClient        ] [node-1] Snapshot downloaded to /tmp/opensearch-13048947992025818328/1901695_1746459961.zip
[2025-05-09T11:40:46,151][INFO ][c.w.c.u.Unzip            ] [node-1] [/tmp/opensearch-13048947992025818328/1901695_1746459961.zip] filePath unzipped to [/tmp/opensearch-13048947992025818328]
[2025-05-09T11:42:17,126][INFO ][c.w.c.i.ContentIndex     ] [node-1] Snapshot indexing finished successfully in 90974 ms
[2025-05-09T11:42:17,206][WARN ][c.w.c.c.CommandManagerClient] [node-1] Unexpected response code: 401
```

## No initialization when offset != 0 :green_circle: 
```
2025-05-09T11:48:09,117][INFO ][c.w.c.i.ContextIndex     ] [node-1] Fetched consumer from the [wazuh-context] index: ConsumerInfo{context='vd_1.0.0', name='vd_4.8.0', offset=1901647, lastOffset=1923009, lastSnapshotLink='https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1901695_1746459961.zip'}
[2025-05-09T11:48:09,312][INFO ][c.w.s.SetupPlugin        ] [node-1] Task scheduled successfully, response: CREATED
[2025-05-09T11:48:09,315][INFO ][c.w.c.CommandManagerPlugin] [node-1] Scheduled task successfully, response: CREATED
[2025-05-09T11:48:09,561][INFO ][c.w.c.c.CTIClient        ] [node-1] Operation succeeded: status code 200 - {"data":{"id":4,"name":"vd_4.8.0","context":"vd_1.0.0","operations":null,"inserted_at":"2023-11-23T19:34:18.698495Z","updated_at":"2025-05-08T13:09:46.817821Z","changes_url":"cti.wazuh.com/api/v1/catalog/contexts/vd_1.0.0/consumers/vd_4.8.0/changes","last_offset":1923009,"last_snapshot_at":"2025-05-05T15:46:01.391685Z","last_snapshot_link":"https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1901695_1746459961.zip","last_snapshot_offset":1901695,"paths_filter":null}}
[2025-05-09T11:48:09,562][INFO ][c.w.c.u.SnapshotManager  ] [node-1] Consumer already initialized (offset 1901647 != 0). Skipping...
```

**Review by Jorgesnchz — APPROVED** [review]
