### PR TITLE
Refactor Content Manager's code and fix Catalog info indexing

### LINKED ISSUE #316: Content Manager refactor I
## Description

We are facing some problems to continue the development of the Content Manager due to some missing pieces of code and missing features, such as the initialization of the snapshot link into the `wazuh-context` index.

## Functional requirements

- The Content Manager initializes the `wazuh-context` index on start.
  - The `snapshot` value is set to a valid link.
  - The `offset` value is set to 0.
  - The `last_offset` value is set to the offset value returned by the request to the CTI API.

## Implementation restrictions

- The `wazuh-context` index is initialized with the content returned by the CTI API, by performing an HTTP request.

## Plan

- [x] Rename `ContextConsumerCatalog` to `ConsumerInfo`
- [x] Get the consumer info from the CTI API and index the data at `onNodeStarted()`
- [x] Remove all test-related code (endpoints). Move the logic inside the plugin or unit tests
- [x] Rename `CTIclient::getConsumerInfo()` to `ConsumerInfo` (a model representing the response from [API Documentation](https://github.com/wazuh/cti/blob/main/docs/API.md#get-apiv1catalogcontextscontextconsumersconsumer))
- [x] Simplify methods in the `ContentIndex` class. Keep only the method `ContextIndex::set(consumerInfo: ConsumerInfo): FutureComplete`, which:
    * Writes `consumerInfo` into the index.
    * Stores the fields: `context`, `name`, `last_offset`, and `last_snapshot_link`
- [x] Reduce the model to only the fields that will be used; the rest can be ignored for now
- [x] Review, simplify, and unify the models
  - [x] Remove `Document`, `GenericDocument`, `Offset`, `Offsets` / Unify them into a new model `ContextChanges`

#### Sample document:

```json
[
  {
    "_index": "wazuh-context",
    "_id": "context-foo",
    "_source": {
      "consumer-bar": {
        "offset": 0,
        "last_offset": 44,
        "snapshot": "uri-to-snapshot"
      }
    }
  }
]
```

### PR DESCRIPTION
**Pull request by f-galland**
### Description
This PR cleans up old test code and fixes indexing of catalog information as retrieved from the CTI API

### Issues Resolved
Closes #316

### CODE REVIEW

**Review by QU3B1M — APPROVED** [review]
LGTM!

`wazuh-context` Index is generated and populates at startup
```shellsession
% curl -sk "http://localhost:9200/wazuh-context/_search"
{"took":29,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":1,"relation":"eq"},"max_score":1.0,"hits":[{"_index":"wazuh-context","_id":"vd_1.0.0","_score":1.0,"_source":{"vd_4.8.0":{"last_offset":1572540,"last_snapshot_link":"https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1532540_1742207528.zip","offset":0}}}]}}
```

File: plugins/content-manager/src/main/java/com/wazuh/contentmanager/index/ContextIndex.java [hunk 1]
```diff
@@ -18,303 +18,118 @@
...
+     * Get a context off its index
      *
-     * @return el RestStatus of get all documents
+     * @param contextName ID of the context to be retrieved
+     * @return A completable future holding the response of the query
      */
-    public CompletableFuture<RestStatus> getAll() {
-        final CompletableFuture<RestStatus> future = new CompletableFuture<>();
-        final ExecutorService executor = this.threadPool.executor(ThreadPool.Names.WRITE);
+    public CompletableFuture<SearchResponse> get(String contextName) {
```
Comment (AlexRuiz7) [inline plugins/content-manager/src/main/java/com/wazuh/contentmanager/index/ContextIndex.java:103]: This method needs to return an exact hit

Consider this JSON
```json
[
  {
    "_index": "wazuh-context",
    "_id": "context-foo",
    "_source": {
      "consumer-bar-A": {
        "offset": 0,
        "last_offset": 44,
        "snapshot": "uri-to-snapshot"
      },
      "consumer-bar-B": {
        "offset": 0,
        "last_offset": 44,
        "snapshot": "uri-to-snapshot"
      }
    }
  }
]
```

Then, we'll want to get one of the consumers. For example, "consumer-bar-A". The method's interface would then be `get(String content, String consumer)`

File: plugins/content-manager/src/main/java/com/wazuh/contentmanager/index/ContextIndex.java [hunk 2]
```diff
@@ -18,303 +18,118 @@
...
-    }
-
-    /**
-     * Update an existing document
-     *
-     * @param id of document
-     * @param document to update the source of the previous document
-     * @return UpdateResponse
-     */
-    public CompletableFuture<RestStatus> update(String id, Document document) {
```
Comment (AlexRuiz7) [inline plugins/content-manager/src/main/java/com/wazuh/contentmanager/index/ContextIndex.java:240]: We are losing this functionality. Bear in mind that we'll need to update the consumer's info during the periodic updates (last_offset, snapshot) and during the patching (offset, last_offset). 

The method's interface would then be `update(String content, String consumer, ConsumerInfo data)`

**Review by AlexRuiz7 — CHANGES_REQUESTED** [review]

**Review by AlexRuiz7 — COMMENTED** [review]
```log
[2025-03-20T16:20:31,615][INFO ][c.w.c.i.ContextIndex     ] [integTest-0] Consumer [vd_1.0.0], indexed with status vd_1.0.0
```

**Review by AlexRuiz7 — APPROVED** [review]
- Code review: ✔️ 
- Test: ✔️ 

The `wazuh-context` index is properly initialized.

```json
{
  "took": 36,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 1,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "wazuh-context",
        "_id": "vd_1.0.0",
        "_score": 1,
        "_source": {
          "vd_4.8.0": {
            "last_offset": 1602540,
            "last_snapshot_link": "https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1532540_1742207528.zip",
            "offset": 0
          }
        }
      }
    ]
  }
}
```

**Comment by f-galland** [comment]
> Here, this logging is duplicated. We can remove the first one, or reword it as follows
> 
> > Sending GET request to [https://cti.wazuh.com/api/v1/catalog/contexts/vd_1.0.0/consumers/vd_4.8.0]
> > Server replied with [status]

We cannot get the second log into the same line in the `HttpClient` since we still do not have the response from the server at that point. These two logs were meant for testing that we were reaching these lines. I'm removing the second log.
